import static org.junit.Assert.assertEquals;

import dungeon.Dungeon;
import dungeon.DungeonController;
import dungeon.IDungeon;
import dungeon.IDungeonController;
import org.junit.Before;
import org.junit.Test;
import randomize.MockRandomnessForWrappedWithMonsters;

import java.io.StringReader;

/**
 * A test for the controller when using an unwrapped dungeon.
 */

public class IDungeonControllerTestForWrapped {
  private IDungeon dungeon;

  /**
   * Sets up all the variables needed before testing.
   */

  @Before
  public void setUp() {
    dungeon = new Dungeon(2, "Ben", true, 6, 8,
            20,4, new MockRandomnessForWrappedWithMonsters());
  }

  /**
   * A test that shows a run of the game where the player emerges victorious.
   */
  @Test
  public void testShowingThePlayerWinning() {
    StringReader input = new StringReader("M S M N P arrow M W M E M N P arrow "
            + "M N M N M N P arrow M S M S M W M N M S M S M W "
            + "M S M W M E M N M N M W M S M N M N M E M N "
            + "S W 1 S W 1 M W M N M E M E M S M N M W M W M S "
            + "M W P arrow M S M N M W M N M N M E P arrow "
            + "M S M N M N M W M E M N M W M N M W P arrow"
            + " M E M S M W M W M E M S M W M E "
            + "S S 2 S S 2 M S M S S W 1 S W 1 M W M E M S P arrow"
            + " M W M S M N M E M N M N S W 1 S W 1 M W ");

    Appendable output = new StringBuilder();
    IDungeonController controller = new DungeonController(output, input);
    controller.playGame(dungeon);

    String expectedOutput =
        "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 0, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 5, column 1. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 4, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (^v) which is at row 4, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 3, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 2, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v) which is at row 1, column 2. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (v) which is at row 1, column 2. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 2, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 3, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 3, column 1. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v) which is at row 2, column 1. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 3, column 1. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 4, column 1. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 4, column 0. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 5, column 0. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 5, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 5, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 4, column 0. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 3, column 0. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 3, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 4, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 3, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 2, column 7. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 2, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 1, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-v) which is at row 1, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-v) which is at row 1, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^->) which is at row 1, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 0, column 7. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-->) which is at row 0, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 0, column 1. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 1, column 1. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 0, column 1. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-->) which is at row 0, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 0, column 7. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^->) which is at row 1, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 1, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 1, column 6. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 2, column 6. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 1, column 6. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^->) which is at row 1, column 5. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 0, column 5. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 5, column 5. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 0, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 6. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 4, column 5. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 6. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 3, column 6. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^->) which is at row 3, column 5. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 2, column 5. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 2, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (->) which is at row 2, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 2, column 5. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^->) which is at row 3, column 5. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 3, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 3, column 3. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 3, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 4, column 3. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 8 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 7 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 4, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 5, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 0, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 0, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 0, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 0, column 3. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 0, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 1, column 4. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (<-^) which is at row 1, column 4. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 1, column 3. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 2, column 3. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 1, column 3. The room is a tunnel : true. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 1, column 4. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 0, column 4. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 5, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 5, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "No. of caves/ distance? \n"
        + "Shot successful! You hear a great howl in the distance\n"
        + "\n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 5, column 4. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "\n"
        + "You are victorious!";

    assertEquals(expectedOutput, output.toString());
  }

  /**
   * A test that shows a run of the game where the player is defeated.
   */
  @Test
  public void testShowingThePlayerDefeated() {
    StringReader input = new StringReader("M S M N P arrow M W M E M N P arrow "
            + "M N M N M N P arrow M S M S M W M N M S M S M W "
            + "M S M W M E M N M N M W M S M N M N M E M N M W");

    Appendable output = new StringBuilder();
    IDungeonController controller = new DungeonController(output, input);
    controller.playGame(dungeon);

    String expectedOutput =
        "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 0, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 3 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 5, column 1. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 5, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 4, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 4 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (^v) which is at row 4, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 3, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 2, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v) which is at row 1, column 2. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 5 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "What? \n"
        + "You pick up an arrow\n"
        + "\n"
        + "Ben is in room (v) which is at row 1, column 2. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v) which is at row 2, column 2. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v) which is at row 3, column 2. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 3, column 1. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v) which is at row 2, column 1. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^v->) which is at row 3, column 1. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 4, column 1. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 4, column 0. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 5, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (->) which is at row 5, column 7. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 5, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 4, column 0. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v->) which is at row 3, column 0. The room is a tunnel : false."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 3, column 7. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^) which is at row 4, column 7. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (^v->) which is at row 3, column 7. The room is a tunnel : false. "
        + "Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (v->) which is at row 2, column 7. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a NO_SMELL\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-^) which is at row 2, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows."
        + " The player smells a PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "Ben is in room (<-v) which is at row 1, column 0. The room is a tunnel : true."
        + " Player has 0 sapphires, 0 diamonds, 0 rubies, and 6 arrows. "
        + "The player smells a VERY_PUNGENT\n"
        + "Move, Pickup, or Shoot (M-P-S)? \n"
        + "Where to? \n"
        + "\n"
        + "\n"
        + "Chomp, chomp, chomp, you are eaten by an Otyugh!\n"
        + "Better luck next time";

    assertEquals(expectedOutput, output.toString());
  }
}
